export const data = [
  { id: 1, name: "Prestigio", model: "Prestigio MultiPhone 4500 Duo" },
  { id: 2, name: "Haier", model: "Haier V6000" },
  { id: 3, name: "Allview", model: "Allview P1 AllDro" },
  { id: 4, name: "Samsung", model: "Samsung U380 Brightside" },
  { id: 5, name: "Nokia", model: "Nokia 6280" },
  { id: 6, name: "BenQ-Siemens", model: "BenQ-Siemens EF81" },
  { id: 7, name: "Sharp", model: "Sharp SE-02" },
  { id: 8, name: "Yezz", model: "Yezz Andy 4.7T" },
  { id: 9, name: "Lenovo", model: "Lenovo Lemon 3" },
  { id: 10, name: "Samsung", model: "Samsung Gear S3 classic" },
  { id: 11, name: "Honor", model: "Honor 10X Lite" },
  { id: 12, name: "Acer", model: "Acer DX650" },
  { id: 13, name: "XOLO", model: "XOLO Q700s plus" },
  { id: 14, name: "Nokia", model: "Nokia 6288" },
  { id: 15, name: "Unnecto", model: "Unnecto Air 5.0" },
  { id: 16, name: "Celkon", model: "Celkon C22" },
  { id: 17, name: "verykool", model: "verykool s5524 Maverick III Jr." },
  { id: 18, name: "HTC", model: "HTC Tattoo" },
  { id: 19, name: "LG", model: "LG GW910" },
  { id: 20, name: "Eten", model: "Eten G500+" },
];
